import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { getSocialConnectUrl } from "@/lib/social.functions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
import { Instagram, Video, ShieldCheck } from "lucide-react";
import { useEffect } from "react";
export const Route=createFileRoute("/dashboard/social")({component:SocialSettings});
function SocialSettings(){const connect=useServerFn(getSocialConnectUrl);const connectPlatform=async(platform:"tiktok"|"instagram")=>{try{const{url}=await connect({data:{platform}});window.location.href=url}catch(e:any){toast.error(e?.message||"Configure as credenciais da rede social primeiro.")}};useEffect(()=>{const p=new URLSearchParams(window.location.search);const status=p.get("connected");if(status==="tiktok")toast.success("TikTok conectado!");if(status==="instagram")toast.success("Instagram conectado!");if(status==="error")toast.error("Não foi possível concluir a conexão.")},[]);return <div className="max-w-4xl mx-auto space-y-6"><div><h2 className="text-[#D4AF37] text-2xl font-light">Redes sociais</h2><p className="text-[#FAFAFA]/60 mt-1">Conecte suas contas para publicar os vídeos exportados diretamente.</p></div><div className="grid md:grid-cols-2 gap-5"><Card className="bg-[#121212] border-[#D4AF37]/20"><CardHeader><CardTitle className="text-white flex items-center gap-3"><Video className="text-[#D4AF37]"/>TikTok</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-white/60">Autorize o aplicativo a publicar vídeos em seu nome. O token fica no servidor.</p><Button className="w-full bg-[#D4AF37] text-black hover:bg-[#B8962E]" onClick={()=>connectPlatform("tiktok")}>Conectar TikTok</Button></CardContent></Card><Card className="bg-[#121212] border-[#D4AF37]/20"><CardHeader><CardTitle className="text-white flex items-center gap-3"><Instagram className="text-[#D4AF37]"/>Instagram</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-white/60">Conecte uma conta profissional habilitada para publicação de Reels.</p><Button className="w-full bg-[#D4AF37] text-black hover:bg-[#B8962E]" onClick={()=>connectPlatform("instagram")}>Conectar Instagram</Button></CardContent></Card></div><div className="rounded-lg border border-[#D4AF37]/15 p-4 flex gap-3 text-sm text-white/60"><ShieldCheck className="h-5 w-5 shrink-0 text-[#D4AF37]"/>A publicação só acontece depois de você autorizar cada rede e iniciar a publicação no aplicativo.</div></div>}
