import {createFileRoute} from "@tanstack/react-router";
import {useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Slider} from "@/components/ui/slider";
import {Upload,Play,Pause} from "lucide-react";
import {toast} from "sonner";
import {supabase} from "@/integrations/supabase/client";
import {ProVideoEditor} from "@/components/video/ProVideoEditor";
import type {VideoProjectSettings} from "@/lib/video/types";
export const Route=createFileRoute("/dashboard/studio-pro")({component:StudioPro});
function SyncPreview({s,onChange}:{s:VideoProjectSettings;onChange:(s:VideoProjectSettings)=>void}){const v=useRef<HTMLVideoElement>(null),a=useRef<HTMLAudioElement>(null);const[playing,setPlaying]=useState(false);const[time,setTime]=useState(0);const offset=s.audio?.offset??0;const setOffset=(n:number)=>{if(s.audio)onChange({...s,audio:{...s.audio,offset:n}})};const toggle=async()=>{if(!v.current||!a.current||!s.audio)return;if(playing){v.current.pause();a.current.pause();setPlaying(false);return}a.current.currentTime=Math.max(0,v.current.currentTime+offset);await Promise.allSettled([v.current.play(),a.current.play()]);setPlaying(true)};return <Card className="bg-[#0A0A0A] border-[#D4AF37]/20"><CardContent className="p-4 space-y-3"><h3 className="text-white font-medium">Pré-visualização de sincronização</h3><p className="text-xs text-white/50">Teste o áudio em relação ao playhead antes de exportar.</p>{s.clips[0]&&<video ref={v} src={s.clips[0].url} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} className="w-full max-h-80 bg-black rounded" controls/>}{s.audio&&<audio ref={a} src={s.audio.url} className="w-full" controls/>}{s.audio&&<><Label className="text-white">Offset: {offset.toFixed(2)}s</Label><Slider value={[offset]} min={-10} max={10} step={.01} onValueChange={x=>setOffset(x[0]||0)}/><div className="flex justify-between text-xs text-white/40"><span>−10s</span><span>Playhead {time.toFixed(2)}s</span><span>+10s</span></div><Button onClick={toggle} variant="outline">{playing?<Pause className="mr-2 h-4 w-4"/>:<Play className="mr-2 h-4 w-4"/>}{playing?"Parar sincronização":"Testar sincronização"}</Button></>}</CardContent></Card>}
function StudioPro(){const ref=useRef<HTMLInputElement>(null);const[id,setId]=useState<string|null>(null),[uid,setUid]=useState<string|null>(null),[title,setTitle]=useState("Novo vídeo"),[settings,setSettings]=useState<VideoProjectSettings>();const upload=async(f:File)=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;setUid(user.id);const path=`${user.id}/${crypto.randomUUID()}-${f.name}`;const u=await supabase.storage.from("videos").upload(path,f,{contentType:f.type});if(u.error)return toast.error(u.error.message);const url=supabase.storage.from("videos").getPublicUrl(path).data.publicUrl;const p=await supabase.from("video_projects").insert({user_id:user.id,title,source_url:url,source_path:path,settings:{},status:"draft"}).select("id").single();if(p.error)return toast.error(p.error.message);setId(p.data.id);setSettings({clips:[{id:crypto.randomUUID(),url,name:f.name,start:0,end:0,duration:0,sourcePath:path}],texts:[],aspect:"9:16",resolution:"1080p",fps:30,preset:"tiktok-1080-30",volume:1,speed:1,filter:"none",motionTransfer:"none",loopLive:false,loopCount:1})};const save=async(s:VideoProjectSettings)=>{setSettings(s);if(id)await supabase.from("video_projects").update({title,settings:s,status:"ready"}).eq("id",id)};return <div className="space-y-4"><h1 className="text-3xl font-semibold text-white">Studio Pro</h1>{!settings?<Card className="bg-[#0A0A0A]"><CardContent className="p-10 text-center"><input ref={ref} hidden type="file" accept="video/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><Upload className="mx-auto text-[#D4AF37]"/><Button className="mt-4" onClick={()=>ref.current?.click()}>Enviar vídeo</Button></CardContent></Card>:<><Label className="text-white">Nome do projeto</Label><Input value={title} onChange={e=>setTitle(e.target.value)}/><ProVideoEditor initial={settings} onChange={setSettings} onExport={async(s,p)=>{await save(s);const m=await import("@/lib/video/export");await m.renderProjectAndUpload({settings:s,projectId:id!,userId:uid!,onProgress:p})}}/><SyncPreview s={settings} onChange={setSettings}/></>}</div>}
