import { createFileRoute, useNavigate, Outlet } from "@tanstack/react-router";
import { SidebarProvider, Sidebar, SidebarContent, SidebarGroup, SidebarGroupLabel, SidebarGroupContent, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Package, FileText, LogOut, User, ShieldCheck, Video, Share2, Send, WandSparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useEffect, useState } from "react";
import { checkIsAdmin } from "@/lib/admin.functions";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
export const Route=createFileRoute("/dashboard")({component:Dashboard});
function Dashboard(){const navigate=useNavigate();const[user,setUser]=useState<any>(null);const checkIsAdminFn=useServerFn(checkIsAdmin);const{data:isAdmin}=useQuery({queryKey:["is-admin"],queryFn:()=>checkIsAdminFn(),enabled:!!user});useEffect(()=>{supabase.auth.getUser().then(({data:{user}})=>{if(!user)navigate({to:"/" as any});else setUser(user)})},[navigate]);const logout=async()=>{await supabase.auth.signOut();navigate({to:"/" as any})};if(!user)return null;const item=(to:string,icon:React.ReactNode,label:string)=><SidebarMenuItem><SidebarMenuButton onClick={()=>navigate({to:to as any})} className="text-[#FAFAFA] hover:bg-[#D4AF37]/10"><span className="mr-2">{icon}</span><span>{label}</span></SidebarMenuButton></SidebarMenuItem>;return <SidebarProvider><div className="flex min-h-screen w-full bg-[#0A0A0A]"><Sidebar className="border-r border-[#D4AF37]/20 bg-[#121212]"><SidebarContent><SidebarGroup><SidebarGroupLabel className="text-[#D4AF37]/60">Menu</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{item("/dashboard/studio",<WandSparkles className="h-4 w-4"/>,"Studio de Vídeo")}{item("/dashboard",<Package className="h-4 w-4"/>,"Meus Produtos")}{item("/dashboard/roteiros",<FileText className="h-4 w-4"/>,"Roteiros Gerados")}{item("/dashboard/videos",<Video className="h-4 w-4"/>,"Meus Vídeos")}{item("/dashboard/publish",<Send className="h-4 w-4"/>,"Publicar vídeos")}{item("/dashboard/social",<Share2 className="h-4 w-4"/>,"Redes sociais")}{item("/dashboard/customers",<User className="h-4 w-4"/>,"Clientes")}{item("/dashboard/profile",<User className="h-4 w-4"/>,"Perfil")}{isAdmin&&<SidebarMenuItem><SidebarMenuButton onClick={()=>navigate({to:"/admin" as any})} className="text-[#D4AF37] hover:bg-[#D4AF37]/10"><ShieldCheck className="mr-2 h-4 w-4"/><span>Painel Admin</span></SidebarMenuButton></SidebarMenuItem>}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent></Sidebar><main className="flex-1 flex flex-col min-w-0"><header className="h-16 border-b border-[#D4AF37]/20 bg-[#121212] flex items-center justify-between px-4 md:px-8 sticky top-0 z-10"><div className="flex items-center gap-4"><SidebarTrigger className="text-[#D4AF37] md:hidden"/><h1 className="text-[#D4AF37] font-light text-lg md:text-xl">Dashboard</h1></div><div className="flex items-center gap-2"><span className="hidden sm:block text-sm text-white/70 truncate max-w-[180px]">{user.email}</span><Button variant="ghost" size="sm" onClick={logout} className="text-[#D4AF37]"><LogOut className="h-4 w-4 mr-2"/>Sair</Button></div></header><div className="p-4 md:p-8"><Outlet/></div></main></div></SidebarProvider>}
