import React, { useState, useRef, useEffect, useCallback, useMemo } from "react";
import { Slider } from "@/components/ui/slider";
import { Button } from "@/components/ui/button";
import { Scissors, Volume2, Type, Play, Pause, Save, Loader2, RotateCcw, Gauge, Sparkles, Plus, Trash2, SkipBack, SkipForward, ZoomIn, ZoomOut, ArrowUp, ArrowDown, Eye, EyeOff, Diamond, Download } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { useUiText } from "@/lib/uiText";
import { exportVideo } from "@/lib/video/export";

interface VideoEditorProps { videoUrl: string; onSave: (settings: EditorSettings) => Promise<void>; initialSettings?: EditorSettings; }
export interface TextOverlay { id: string; text: string; start: number; end: number; size: number; color: string; background: boolean; y: number; }
export interface EffectKeyframe { id: string; time: number; intensity: number; }
export interface EffectLayer { id: string; motion: MotionKey; intensity: number; speed: number; start: number; end: number; enabled: boolean; keyframes: EffectKeyframe[]; }
export interface AudioFx { bass: number; treble: number; echo: number; echoTime: number; pitch: number; preset?: AudioPresetKey; }
export interface EditorSettings { startTime: number; endTime: number; volume: number; subtitle?: string; subtitleSize?: number; subtitleColor?: string; speed?: number; aspect?: "original"|"9:16"|"1:1"|"16:9"; filter?: FilterKey; brightness?: number; contrast?: number; saturation?: number; fadeIn?: boolean; fadeOut?: boolean; motion?: MotionKey; motionIntensity?: number; motionSpeed?: number; effects?: EffectLayer[]; audioFx?: AudioFx; texts?: TextOverlay[]; }

type AudioPresetKey = "none"|"podcast"|"radio"|"cinema"|"grave"|"telefone"|"arena";
const AUDIO_PRESETS: Record<AudioPresetKey,{label:string;fx:Omit<AudioFx,"preset">}>={none:{label:"Original",fx:{bass:0,treble:0,echo:0,echoTime:.25,pitch:1}},podcast:{label:"Podcast",fx:{bass:3,treble:4,echo:0,echoTime:.2,pitch:1}},radio:{label:"Rádio",fx:{bass:6,treble:6,echo:8,echoTime:.15,pitch:1}},cinema:{label:"Cinema",fx:{bass:8,treble:2,echo:18,echoTime:.35,pitch:1}},grave:{label:"Grave",fx:{bass:12,treble:-4,echo:0,echoTime:.25,pitch:1}},telefone:{label:"Telefone",fx:{bass:-12,treble:-6,echo:0,echoTime:.2,pitch:1}},arena:{label:"Arena",fx:{bass:4,treble:1,echo:45,echoTime:.5,pitch:1}}};
type FilterKey="none"|"vivid"|"cinema"|"bw"|"vintage"|"cool"|"warm";
const FILTERS:Record<FilterKey,{label:string;css:string}>={none:{label:"Original",css:""},vivid:{label:"Vívido",css:"saturate(1.5) contrast(1.1)"},cinema:{label:"Cinema",css:"contrast(1.2) saturate(.9) sepia(.15)"},bw:{label:"P&B",css:"grayscale(1) contrast(1.1)"},vintage:{label:"Vintage",css:"sepia(.45) contrast(.95) saturate(1.2)"},cool:{label:"Frio",css:"hue-rotate(-12deg) saturate(1.1)"},warm:{label:"Quente",css:"hue-rotate(12deg) saturate(1.2) brightness(1.05)"}};
type MotionKey="none"|"zoomIn"|"zoomOut"|"kenburns"|"pulse"|"shake"|"swing"|"glitch"|"flash"|"slideIn";
const MOTIONS:Record<MotionKey,{label:string;anim:string;loop:boolean}>={none:{label:"Nenhum",anim:"",loop:false},zoomIn:{label:"Zoom in",anim:"ve-zoom-in",loop:false},zoomOut:{label:"Zoom out",anim:"ve-zoom-out",loop:false},kenburns:{label:"Ken Burns",anim:"ve-kenburns",loop:true},pulse:{label:"Batida",anim:"ve-pulse",loop:true},shake:{label:"Tremor",anim:"ve-shake",loop:true},swing:{label:"Balanço",anim:"ve-swing",loop:true},glitch:{label:"Glitch",anim:"ve-glitch",loop:true},flash:{label:"Flash",anim:"ve-flash",loop:true},slideIn:{label:"Entrada",anim:"ve-slide-in",loop:false}};
const ASPECTS={original:"aspect-video","9:16":"aspect-[9/16]","1:1":"aspect-square","16:9":"aspect-video"};
const DEFAULTS:EditorSettings={startTime:0,endTime:0,volume:1,speed:1,aspect:"original",filter:"none",brightness:100,contrast:100,saturation:100,fadeIn:false,fadeOut:false,motion:"none",motionIntensity:50,motionSpeed:1,effects:[],audioFx:{bass:0,treble:0,echo:0,echoTime:.25,pitch:1,preset:"none"},texts:[]};
const uid=()=>globalThis.crypto?.randomUUID?.()??`id-${Math.random().toString(36).slice(2)}`;
export function makeLayer(motion:MotionKey,patch:Partial<EffectLayer>={}):EffectLayer{return{id:uid(),motion,intensity:50,speed:1,start:0,end:0,enabled:true,keyframes:[],...patch};}
const EFFECT_PRESETS=[{key:"viral",label:"Viral TikTok",filter:"vivid" as FilterKey,build:()=>[makeLayer("zoomIn",{intensity:40}),makeLayer("pulse",{intensity:35,speed:1.6})]},{key:"hook",label:"Hook forte",filter:"vivid" as FilterKey,build:()=>[makeLayer("slideIn",{intensity:70,speed:1.4}),makeLayer("flash",{intensity:45,speed:2})]},{key:"cinema",label:"Cinematográfico",filter:"cinema" as FilterKey,build:()=>[makeLayer("kenburns",{intensity:30,speed:.6})]},{key:"energia",label:"Energia",filter:"warm" as FilterKey,build:()=>[makeLayer("shake",{intensity:35,speed:2}),makeLayer("pulse",{intensity:45,speed:2.2})]},{key:"retro",label:"Retrô glitch",filter:"vintage" as FilterKey,build:()=>[makeLayer("glitch",{intensity:50,speed:1.5}),makeLayer("swing",{intensity:25,speed:.8})]},{key:"suave",label:"Suave",filter:"cool" as FilterKey,build:()=>[makeLayer("zoomOut",{intensity:20,speed:.5})]}];
function migrate(s?:EditorSettings):EditorSettings{if(!s)return{...DEFAULTS};const m={...DEFAULTS,...s,audioFx:{...DEFAULTS.audioFx!,...(s.audioFx??{})}};if((!m.effects||!m.effects.length)&&s.motion&&s.motion!=="none")m.effects=[makeLayer(s.motion,{intensity:s.motionIntensity??50,speed:s.motionSpeed??1})];m.effects=(m.effects??[]).map(l=>({...makeLayer(l.motion),...l,keyframes:l.keyframes??[]}));if((!m.texts||!m.texts.length)&&s.subtitle)m.texts=[{id:uid(),text:s.subtitle,start:s.startTime??0,end:s.endTime??0,size:s.subtitleSize??24,color:s.subtitleColor??"#fff",background:true,y:82}];return m;}
export function intensityAt(l:EffectLayer,t:number){const k=[...(l.keyframes??[])].sort((a,b)=>a.time-b.time);if(!k.length)return l.intensity;if(t<=k[0]!.time)return k[0]!.intensity;if(t>=k[k.length-1]!.time)return k[k.length-1]!.intensity;for(let i=0;i<k.length-1;i++){const a=k[i]!,b=k[i+1]!;if(t>=a.time&&t<=b.time){const r=(t-a.time)/(b.time-a.time||1);return a.intensity+(b.intensity-a.intensity)*r;}}return l.intensity;}
const fmt=(t:number)=>{if(!isFinite(t))return"0:00.0";return`${Math.floor(t/60)}:${(t%60).toFixed(1).padStart(4,"0")}`};

export function VideoEditor({videoUrl,onSave,initialSettings}:VideoEditorProps){
 const videoRef=useRef<HTMLVideoElement>(null),timelineRef=useRef<HTMLDivElement>(null); const [duration,setDuration]=useState(0),[currentTime,setCurrentTime]=useState(0),[isPlaying,setIsPlaying]=useState(false),[isSaving,setIsSaving]=useState(false),[isExporting,setIsExporting]=useState(false),[exportProgress,setExportProgress]=useState(0),[zoom,setZoom]=useState(1),[drag,setDrag]=useState<null|"start"|"end"|"playhead">(null),[selectedTextId,setSelectedTextId]=useState<string|null>(null); const[settings,setSettings]=useState<EditorSettings>(()=>migrate(initialSettings));
 const set=useCallback(<K extends keyof EditorSettings>(k:K,v:EditorSettings[K])=>setSettings(s=>({...s,[k]:v})),[]);
 useEffect(()=>{const v=videoRef.current;if(!v)return;const meta=()=>{const d=v.duration||0;setDuration(d);setSettings(s=>({...s,endTime:s.endTime&&s.endTime>0?Math.min(s.endTime,d):d}))};const time=()=>{setCurrentTime(v.currentTime);const end=settings.endTime||v.duration;if(v.currentTime>=end){v.currentTime=settings.startTime;v.pause();setIsPlaying(false)}};const ended=()=>setIsPlaying(false);v.addEventListener("loadedmetadata",meta);v.addEventListener("timeupdate",time);v.addEventListener("ended",ended);if(v.readyState>=1)meta();return()=>{v.removeEventListener("loadedmetadata",meta);v.removeEventListener("timeupdate",time);v.removeEventListener("ended",ended)}},[settings.startTime,settings.endTime]);
 useEffect(()=>{const v=videoRef.current;if(v){v.volume=settings.volume??1;v.playbackRate=settings.speed??1}},[settings.volume,settings.speed]);
 const togglePlay=()=>{const v=videoRef.current;if(!v)return;if(isPlaying){v.pause();setIsPlaying(false)}else{if(v.currentTime<settings.startTime||v.currentTime>=(settings.endTime||duration))v.currentTime=settings.startTime;void v.play();setIsPlaying(true)}};
 const seek=(t:number)=>{const c=Math.max(0,Math.min(t,duration||0));if(videoRef.current)videoRef.current.currentTime=c;setCurrentTime(c)};
 const timeFromEvent=(x:number)=>{const el=timelineRef.current;if(!el||!duration)return 0;const r=el.getBoundingClientRect();return Math.max(0,Math.min(((x-r.left+el.scrollLeft)/(r.width*zoom))*duration,duration))};
 useEffect(()=>{if(!drag)return;const move=(e:MouseEvent|TouchEvent)=>{const x="touches"in e?(e.touches[0]?.clientX??0):e.clientX,t=timeFromEvent(x);if(drag==="start")setSettings(s=>({...s,startTime:Math.min(t,(s.endTime||duration)-.2)}));else if(drag==="end")setSettings(s=>({...s,endTime:Math.max(t,s.startTime+.2)}));else seek(t)};const up=()=>setDrag(null);window.addEventListener("mousemove",move);window.addEventListener("touchmove",move);window.addEventListener("mouseup",up);window.addEventListener("touchend",up);return()=>{window.removeEventListener("mousemove",move);window.removeEventListener("touchmove",move);window.removeEventListener("mouseup",up);window.removeEventListener("touchend",up)}},[drag,duration,zoom]);
 const pct=(t:number)=>duration?t/duration*100:0; const activeTexts=useMemo(()=>settings.texts?.filter(t=>currentTime>=t.start&&currentTime<=t.end)??[],[settings.texts,currentTime]); const cssFilter=useMemo(()=>[FILTERS[(settings.filter??"none")as FilterKey].css,`brightness(${(settings.brightness??100)/100})`,`contrast(${(settings.contrast??100)/100})`,`saturate(${(settings.saturation??100)/100})`].filter(Boolean).join(" "),[settings.filter,settings.brightness,settings.contrast,settings.saturation]); const fadeOpacity=useMemo(()=>{const s=settings.startTime,e=settings.endTime||duration,F=.6;if(settings.fadeIn&&currentTime<s+F)return Math.max(0,(currentTime-s)/F);if(settings.fadeOut&&currentTime>e-F)return Math.max(0,(e-currentTime)/F);return 1},[currentTime,settings.fadeIn,settings.fadeOut,settings.startTime,settings.endTime,duration]); const layers=settings.effects??[];
 const layerStyles=useMemo(()=>layers.filter(l=>l.enabled&&MOTIONS[l.motion]?.anim&&currentTime>=(l.start??0)&&currentTime<=(l.end||(settings.endTime||duration)||Infinity)).map(l=>{const m=MOTIONS[l.motion],i=Math.max(0,Math.min(100,intensityAt(l,currentTime)))/100,s=l.speed||1;return{id:l.id,style:{animationName:m.anim,animationDuration:`${Math.max(.25,m.loop?1.6/s:6/s)}s`,animationTimingFunction:l.motion==="shake"||l.motion==="glitch"?"steps(4,end)":"ease-in-out",animationIterationCount:m.loop?"infinite":1,animationFillMode:"both",animationPlayState:isPlaying?"running":"paused",transformOrigin:"center",willChange:"transform,filter",["--ve-amt"as string]:1+.35*i,["--ve-px"as string]:`${Math.round(2+14*i)}px`,["--ve-deg"as string]:`${(.5+4*i).toFixed(2)}deg`,["--ve-bright"as string]:1+1.2*i} as React.CSSProperties}}),[layers,currentTime,isPlaying,duration,settings.endTime]);
 const addLayer=(motion:MotionKey)=>setSettings(s=>({...s,effects:[...(s.effects??[]),makeLayer(motion,{end:s.endTime||0})]})); const updateLayer=(id:string,p:Partial<EffectLayer>)=>setSettings(s=>({...s,effects:(s.effects??[]).map(l=>l.id===id?{...l,...p}:l)})); const removeLayer=(id:string)=>setSettings(s=>({...s,effects:(s.effects??[]).filter(l=>l.id!==id)})); const moveLayer=(id:string,d:-1|1)=>setSettings(s=>{const a=[...(s.effects??[])],i=a.findIndex(l=>l.id===id),j=i+d;if(i<0||j<0||j>=a.length)return s;[a[i],a[j]]=[a[j]!,a[i]!];return{...s,effects:a}}); const applyPreset=(key:string)=>{const p=EFFECT_PRESETS.find(x=>x.key===key);if(!p)return;setSettings(s=>({...s,filter:p.filter,effects:p.build().map(l=>({...l,end:s.endTime||0}))}));toast.success(`Preset "${p.label}" aplicado`)};
 const addKeyframe=(id:string)=>setSettings(s=>({...s,effects:(s.effects??[]).map(l=>l.id===id?{...l,keyframes:[...(l.keyframes??[]),{id:uid(),time:Math.round(currentTime*10)/10,intensity:l.intensity}].sort((a,b)=>a.time-b.time)}:l)})); const updateKeyframe=(id:string,kid:string,p:Partial<EffectKeyframe>)=>setSettings(s=>({...s,effects:(s.effects??[]).map(l=>l.id===id?{...l,keyframes:(l.keyframes??[]).map(k=>k.id===kid?{...k,...p}:k).sort((a,b)=>a.time-b.time)}:l)})); const removeKeyframe=(id:string,kid:string)=>setSettings(s=>({...s,effects:(s.effects??[]).map(l=>l.id===id?{...l,keyframes:(l.keyframes??[]).filter(k=>k.id!==kid)}:l)}));
 const addText=()=>{const t={id:uid(),text:"Novo texto",start:Math.round(currentTime*10)/10,end:Math.min(settings.endTime||duration,currentTime+3),size:28,color:"#fff",background:true,y:82};setSettings(s=>({...s,texts:[...(s.texts??[]),t]}));setSelectedTextId(t.id)}; const updateText=(id:string,p:Partial<TextOverlay>)=>setSettings(s=>({...s,texts:(s.texts??[]).map(t=>t.id===id?{...t,...p}:t)})); const removeText=(id:string)=>setSettings(s=>({...s,texts:(s.texts??[]).filter(t=>t.id!==id)})); const selectedText=settings.texts?.find(t=>t.id===selectedTextId)??null;
 const handleSave=async()=>{setIsSaving(true);try{const f=settings.texts?.[0];await onSave({...settings,subtitle:f?.text??"",subtitleSize:f?.size??24,subtitleColor:f?.color??"#fff"});toast.success("Edição salva com sucesso!")}catch{toast.error("Erro ao salvar a edição.")}finally{setIsSaving(false)}};
 const handleExport=async()=>{setIsExporting(true);setExportProgress(0);try{const blob=await exportVideo(videoUrl,settings,p=>setExportProgress(p));const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`videotiktokshop-${Date.now()}.mp4`;a.click();URL.revokeObjectURL(url);toast.success("Vídeo MP4 exportado com sucesso!")}catch(e:any){console.error(e);toast.error(`Erro ao exportar: ${e?.message||"tente novamente"}`)}finally{setIsExporting(false)}};
 const {t:ui}=useUiText();
 return <div className="space-y-3 sm:space-y-4 w-full min-w-0 overflow-x-hidden">
  <div className="flex justify-center"><div className={cn("relative bg-black rounded-xl overflow-hidden border border-[#D4AF37]/20 group w-full max-h-[34dvh] sm:max-h-[45dvh]",ASPECTS[settings.aspect??"original"],settings.aspect==="9:16"&&"max-w-[200px] sm:max-w-[280px]",settings.aspect==="1:1"&&"max-w-[320px] sm:max-w-[440px]")}><div className="absolute inset-0 overflow-hidden" style={layerStyles[0]?.style??{}}><div className="absolute inset-0 overflow-hidden" style={layerStyles[1]?.style??{}}><div className="absolute inset-0 overflow-hidden" style={layerStyles[2]?.style??{}}><div className="absolute inset-0 overflow-hidden" style={layerStyles[3]?.style??{}}><video ref={videoRef} src={videoUrl} className="w-full h-full object-contain" style={{filter:cssFilter,opacity:fadeOpacity}} playsInline onClick={togglePlay}/></div></div></div></div>{activeTexts.map(t=><div key={t.id} className="absolute left-0 right-0 text-center px-4 pointer-events-none" style={{top:`${t.y}%`,transform:"translateY(-50%)"}}><span className="inline-block font-bold leading-tight drop-shadow-[0_2px_4px_rgba(0,0,0,.9)]" style={{fontSize:t.size,color:t.color,background:t.background?"rgba(0,0,0,.55)":"transparent",padding:t.background?"2px 10px":0,borderRadius:8}}>{t.text}</span></div>)}<div className="absolute top-2 right-3 text-[10px] font-mono text-[#D4AF37] bg-black/60 px-2 py-0.5 rounded">{fmt(currentTime)} / {fmt(duration)}</div></div></div>
  <Card className="bg-[#0A0A0A] border-[#D4AF37]/20"><CardContent className="p-2 sm:p-3 space-y-2"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-widest text-[#D4AF37]/60">{ui("editor.timeline.title")}</span><div className="flex items-center"><Button size="icon" variant="ghost" className="h-7 w-7 text-[#D4AF37]" onClick={()=>setZoom(z=>Math.max(1,z-.5))}><ZoomOut className="h-3.5 w-3.5"/></Button><span className="text-[10px] text-[#D4AF37]/60 w-8 text-center">{zoom}x</span><Button size="icon" variant="ghost" className="h-7 w-7 text-[#D4AF37]" onClick={()=>setZoom(z=>Math.min(6,z+.5))}><ZoomIn className="h-3.5 w-3.5"/></Button></div></div><div ref={timelineRef} className="overflow-x-auto pb-2"><div className="relative select-none" style={{width:`${zoom*100}%`,minWidth:"100%"}}><div className="relative h-10 sm:h-14 rounded-md bg-[#111] border border-[#262626] overflow-hidden" onMouseDown={e=>{setDrag("playhead");seek(timeFromEvent(e.clientX))}}><div className="absolute inset-0 flex">{Array.from({length:24}).map((_,i)=><div key={i} className="flex-1 border-r border-[#D4AF37]/5"/>)}</div><div className="absolute top-0 bottom-0 left-0 bg-black/70" style={{width:`${pct(settings.startTime)}%`}}/><div className="absolute top-0 bottom-0 right-0 bg-black/70" style={{width:`${100-pct(settings.endTime||duration)}%`}}/><div className="absolute top-0 bottom-0 border-y-2 border-[#D4AF37]/70 bg-[#D4AF37]/10" style={{left:`${pct(settings.startTime)}%`,width:`${pct((settings.endTime||duration)-settings.startTime)}%`}}/><div className="absolute top-0 bottom-0 w-3 -ml-1.5 bg-[#D4AF37] rounded cursor-ew-resize" style={{left:`${pct(settings.startTime)}%`}} onMouseDown={e=>{e.stopPropagation();setDrag("start")}}/><div className="absolute top-0 bottom-0 w-3 -ml-1.5 bg-[#D4AF37] rounded cursor-ew-resize" style={{left:`${pct(settings.endTime||duration)}%`}} onMouseDown={e=>{e.stopPropagation();setDrag("end")}}/><div className="absolute top-0 bottom-0 w-[2px] bg-white" style={{left:`${pct(currentTime)}%`}}/></div><div className="relative h-8 mt-1.5 rounded-md bg-[#111] border border-[#262626]">{(settings.texts??[]).map(t=><button key={t.id} onClick={()=>setSelectedTextId(t.id)} className={cn("absolute top-1 bottom-1 rounded px-2 text-[10px] truncate",selectedTextId===t.id?"bg-[#D4AF37] text-black":"bg-[#D4AF37]/25 text-white")} style={{left:`${pct(t.start)}%`,width:`${Math.max(pct(t.end-t.start),4)}%`}}>{t.text||"Texto"}</button>)}</div></div></div><div className="flex justify-between text-[10px] font-mono text-[#D4AF37]/60"><span>Início {fmt(settings.startTime)}</span><span>Duração {fmt(Math.max(0,((settings.endTime||duration)-settings.startTime)/(settings.speed??1)))}</span><span>Fim {fmt(settings.endTime||duration)}</span></div></CardContent></Card>
  <Tabs defaultValue="cortar"><TabsList className="bg-[#0A0A0A] border border-[#D4AF37]/20 w-full grid grid-cols-4 h-auto p-1"><TabsTrigger value="cortar"><Scissors className="h-3.5 w-3.5 mr-1"/>Cortar</TabsTrigger><TabsTrigger value="texto"><Type className="h-3.5 w-3.5 mr-1"/>Texto</TabsTrigger><TabsTrigger value="audio"><Volume2 className="h-3.5 w-3.5 mr-1"/>Áudio</TabsTrigger><TabsTrigger value="efeitos"><Sparkles className="h-3.5 w-3.5 mr-1"/>Efeitos</TabsTrigger></TabsList>
   <TabsContent value="cortar"><Card className="bg-[#0A0A0A] border-[#D4AF37]/20"><CardContent className="p-4 space-y-5"><div className="grid grid-cols-2 gap-3"><Button variant="outline" onClick={()=>set("startTime",Math.min(currentTime,(settings.endTime||duration)-.2))}>Cortar início aqui</Button><Button variant="outline" onClick={()=>set("endTime",Math.max(currentTime,settings.startTime+.2))}>Cortar fim aqui</Button></div><div className="space-y-2"><div className="flex justify-between"><Label>Velocidade</Label><span className="text-xs text-[#D4AF37]">{settings.speed}x</span></div><Slider min={.25} max={3} step={.05} value={[settings.speed??1]} onValueChange={v=>set("speed",v[0]??1)}/></div><div className="grid grid-cols-4 gap-2">{(["original","9:16","1:1","16:9"] as const).map(a=><Button key={a} size="sm" variant="outline" className={cn(settings.aspect===a&&"bg-[#D4AF37] text-black")} onClick={()=>set("aspect",a)}>{a}</Button>)}</div></CardContent></Card></TabsContent>
   <TabsContent value="texto"><Card className="bg-[#0A0A0A] border-[#D4AF37]/20"><CardContent className="p-4 space-y-4"><Button onClick={addText} variant="outline">Adicionar texto</Button>{selectedText&&<div className="grid grid-cols-2 gap-3"><div className="col-span-2"><Label>Texto</Label><Input value={selectedText.text} onChange={e=>updateText(selectedText.id,{text:e.target.value})}/></div><div><Label>Início</Label><Input type="number" step=".1" value={selectedText.start} onChange={e=>updateText(selectedText.id,{start:Number(e.target.value)})}/></div><div><Label>Fim</Label><Input type="number" step=".1" value={selectedText.end} onChange={e=>updateText(selectedText.id,{end:Number(e.target.value)})}/></div><div><Label>Tamanho</Label><Input type="number" value={selectedText.size} onChange={e=>updateText(selectedText.id,{size:Number(e.target.value)})}/></div><div><Label>Cor</Label><Input type="color" value={selectedText.color} onChange={e=>updateText(selectedText.id,{color:e.target.value})}/></div><Button variant="outline" onClick={()=>removeText(selectedText.id)} className="text-red-400">Excluir texto</Button></div>}</CardContent></Card></TabsContent>
   <TabsContent value="audio"><Card className="bg-[#0A0A0A] border-[#D4AF37]/20"><CardContent className="p-4 space-y-4"><div className="flex justify-between"><Label>Volume</Label><span className="text-xs text-[#D4AF37]">{Math.round((settings.volume??1)*100)}%</span></div><Slider min={0} max={1} step={.01} value={[settings.volume??1]} onValueChange={v=>set("volume",v[0]??1)}/><div className="flex flex-wrap gap-2">{(Object.keys(AUDIO_PRESETS) as AudioPresetKey[]).map(k=><Button key={k} size="sm" variant="outline" className={cn(settings.audioFx?.preset===k&&"bg-[#D4AF37] text-black")} onClick={()=>set("audioFx",{...AUDIO_PRESETS[k].fx,preset:k})}>{AUDIO_PRESETS[k].label}</Button>)}</div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>set("fadeIn",!settings.fadeIn)}>Fade entrada</Button><Button size="sm" variant="outline" onClick={()=>set("fadeOut",!settings.fadeOut)}>Fade saída</Button></div></CardContent></Card></TabsContent>
   <TabsContent value="efeitos"><Card className="bg-[#0A0A0A] border-[#D4AF37]/20"><CardContent className="p-4 space-y-4"><div className="grid grid-cols-2 sm:grid-cols-3 gap-2">{EFFECT_PRESETS.map(p=><Button key={p.key} size="sm" variant="outline" onClick={()=>applyPreset(p.key)}>{p.label}</Button>)}</div><div className="grid grid-cols-3 sm:grid-cols-5 gap-2">{(Object.keys(MOTIONS) as MotionKey[]).filter(k=>k!=="none").map(k=><Button key={k} size="sm" variant="outline" onClick={()=>addLayer(k)}><Plus className="h-3 w-3"/>{MOTIONS[k].label}</Button>)}</div>{layers.map((l,i)=><div key={l.id} className="rounded-lg border border-[#D4AF37]/30 p-3 space-y-3"><div className="flex items-center gap-1"><span className="flex-1">{i+1}. {MOTIONS[l.motion].label}</span><Button size="icon" variant="ghost" onClick={()=>moveLayer(l.id,-1)} disabled={i===0}><ArrowUp/></Button><Button size="icon" variant="ghost" onClick={()=>moveLayer(l.id,1)} disabled={i===layers.length-1}><ArrowDown/></Button><Button size="icon" variant="ghost" onClick={()=>updateLayer(l.id,{enabled:!l.enabled})}>{l.enabled?<Eye/>:<EyeOff/>}</Button><Button size="icon" variant="ghost" onClick={()=>removeLayer(l.id)}><Trash2/></Button></div><div className="grid grid-cols-2 gap-2"><Input type="number" step=".1" value={l.start} onChange={e=>updateLayer(l.id,{start:Number(e.target.value)})}/><Input type="number" step=".1" value={l.end} onChange={e=>updateLayer(l.id,{end:Number(e.target.value)})}/></div><Slider min={5} max={100} step={5} value={[l.intensity]} onValueChange={v=>updateLayer(l.id,{intensity:v[0]??50})}/><Button size="sm" variant="outline" onClick={()=>addKeyframe(l.id)}><Diamond className="h-3 w-3 mr-1"/>Keyframe {fmt(currentTime)}</Button>{(l.keyframes??[]).map(k=><div key={k.id} className="flex gap-2 items-center"><Input type="number" step=".1" value={k.time} onChange={e=>updateKeyframe(l.id,k.id,{time:Number(e.target.value)})}/><Slider min={0} max={100} value={[k.intensity]} onValueChange={v=>updateKeyframe(l.id,k.id,{intensity:v[0]??50})}/><Button size="icon" variant="ghost" onClick={()=>removeKeyframe(l.id,k.id)}><Trash2/></Button></div>)}</div>)}</CardContent></Card></TabsContent>
  </Tabs>
  <div className="flex flex-col sm:flex-row gap-2"><Button onClick={handleSave} disabled={isSaving||isExporting} className="flex-1 bg-[#D4AF37] text-black">{isSaving?<Loader2 className="mr-2 animate-spin"/>:<Save className="mr-2"/>}Salvar edição</Button><Button onClick={handleExport} disabled={isSaving||isExporting} className="flex-1 bg-white text-black hover:bg-white/90">{isExporting?<><Loader2 className="mr-2 animate-spin"/>Exportando {Math.round(exportProgress*100)}%</>:<><Download className="mr-2"/>Exportar MP4</>}</Button><Button variant="outline" onClick={()=>{setSettings({...DEFAULTS,endTime:duration});seek(0)}}><RotateCcw className="mr-2"/>Resetar</Button></div>
 </div>;
}
