/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardRecordRouteImport } from './routes/dashboard.record'
import { Route as DashboardRoteirosIndexRouteImport } from './routes/dashboard.roteiros.index'
import { Route as DashboardRoteirosProductIdRouteImport } from './routes/dashboard.roteiros.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordRoute = DashboardRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoteirosIndexRoute = DashboardRoteirosIndexRouteImport.update({
  id: '/roteiros/',
  path: '/roteiros/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoteirosProductIdRoute =
  DashboardRoteirosProductIdRouteImport.update({
    id: '/roteiros/$productId',
    path: '/roteiros/$productId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/record': typeof DashboardRecordRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/roteiros/$productId': typeof DashboardRoteirosProductIdRoute
  '/dashboard/roteiros/': typeof DashboardRoteirosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/record': typeof DashboardRecordRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/roteiros/$productId': typeof DashboardRoteirosProductIdRoute
  '/dashboard/roteiros': typeof DashboardRoteirosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/record': typeof DashboardRecordRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/roteiros/$productId': typeof DashboardRoteirosProductIdRoute
  '/dashboard/roteiros/': typeof DashboardRoteirosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/record'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/roteiros/$productId'
    | '/dashboard/roteiros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/profile'
    | '/dashboard/record'
    | '/admin'
    | '/dashboard'
    | '/dashboard/roteiros/$productId'
    | '/dashboard/roteiros'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/record'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/roteiros/$productId'
    | '/dashboard/roteiros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/record': {
      id: '/dashboard/record'
      path: '/record'
      fullPath: '/dashboard/record'
      preLoaderRoute: typeof DashboardRecordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roteiros/': {
      id: '/dashboard/roteiros/'
      path: '/roteiros'
      fullPath: '/dashboard/roteiros/'
      preLoaderRoute: typeof DashboardRoteirosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roteiros/$productId': {
      id: '/dashboard/roteiros/$productId'
      path: '/roteiros/$productId'
      fullPath: '/dashboard/roteiros/$productId'
      preLoaderRoute: typeof DashboardRoteirosProductIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRecordRoute: typeof DashboardRecordRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRoteirosProductIdRoute: typeof DashboardRoteirosProductIdRoute
  DashboardRoteirosIndexRoute: typeof DashboardRoteirosIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRecordRoute: DashboardRecordRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRoteirosProductIdRoute: DashboardRoteirosProductIdRoute,
  DashboardRoteirosIndexRoute: DashboardRoteirosIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
