/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminUiTextosRouteImport } from './routes/admin.ui-textos'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardCustomersIndexRouteImport } from './routes/dashboard.customers.index'
import { Route as DashboardRoteirosIndexRouteImport } from './routes/dashboard.roteiros.index'
import { Route as DashboardRoteirosProductIdRouteImport } from './routes/dashboard.roteiros.$productId'
import { Route as DashboardVideosIndexRouteImport } from './routes/dashboard.videos.index'
import { Route as DashboardRecordRoteiroRowIdScriptIdRouteImport } from './routes/dashboard.record.$roteiroRowId.$scriptId'
import { Route as DashboardStudioRouteImport } from './routes/dashboard.studio'
import { Route as DashboardStudioProRouteImport } from './routes/dashboard.studio-pro'
import { Route as DashboardPublishRouteImport } from './routes/dashboard.publish'
import { Route as DashboardSocialRouteImport } from './routes/dashboard.social'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AdminRoute } as any)
const AdminLoginRoute = AdminLoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => AdminRoute } as any)
const AdminUiTextosRoute = AdminUiTextosRouteImport.update({ id: '/ui-textos', path: '/ui-textos', getParentRoute: () => AdminRoute } as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => DashboardRoute } as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => DashboardRoute } as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({ id: '/customers/', path: '/customers/', getParentRoute: () => DashboardRoute } as any)
const DashboardRoteirosIndexRoute = DashboardRoteirosIndexRouteImport.update({ id: '/roteiros/', path: '/roteiros/', getParentRoute: () => DashboardRoute } as any)
const DashboardRoteirosProductIdRoute = DashboardRoteirosProductIdRouteImport.update({ id: '/roteiros/$productId', path: '/roteiros/$productId', getParentRoute: () => DashboardRoute } as any)
const DashboardVideosIndexRoute = DashboardVideosIndexRouteImport.update({ id: '/videos/', path: '/videos/', getParentRoute: () => DashboardRoute } as any)
const DashboardRecordRoteiroRowIdScriptIdRoute = DashboardRecordRoteiroRowIdScriptIdRouteImport.update({ id: '/record/$roteiroRowId/$scriptId', path: '/record/$roteiroRowId/$scriptId', getParentRoute: () => DashboardRoute } as any)
const DashboardStudioRoute = DashboardStudioRouteImport.update({ id: '/studio', path: '/studio', getParentRoute: () => DashboardRoute } as any)
const DashboardStudioProRoute = DashboardStudioProRouteImport.update({ id: '/studio-pro', path: '/studio-pro', getParentRoute: () => DashboardRoute } as any)
const DashboardPublishRoute = DashboardPublishRouteImport.update({ id: '/publish', path: '/publish', getParentRoute: () => DashboardRoute } as any)
const DashboardSocialRoute = DashboardSocialRouteImport.update({ id: '/social', path: '/social', getParentRoute: () => DashboardRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/ui-textos': typeof AdminUiTextosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/roteiros/$productId': typeof DashboardRoteirosProductIdRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/roteiros/': typeof DashboardRoteirosIndexRoute
  '/dashboard/videos/': typeof DashboardVideosIndexRoute
  '/dashboard/record/$roteiroRowId/$scriptId': typeof DashboardRecordRoteiroRowIdScriptIdRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/studio-pro': typeof DashboardStudioProRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/social': typeof DashboardSocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ui-textos': typeof AdminUiTextosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/roteiros/$productId': typeof DashboardRoteirosProductIdRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/dashboard/roteiros': typeof DashboardRoteirosIndexRoute
  '/dashboard/videos': typeof DashboardVideosIndexRoute
  '/dashboard/record/$roteiroRowId/$scriptId': typeof DashboardRecordRoteiroRowIdScriptIdRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/studio-pro': typeof DashboardStudioProRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/social': typeof DashboardSocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/ui-textos': typeof AdminUiTextosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/roteiros/$productId': typeof DashboardRoteirosProductIdRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/roteiros/': typeof DashboardRoteirosIndexRoute
  '/dashboard/videos/': typeof DashboardVideosIndexRoute
  '/dashboard/record/$roteiroRowId/$scriptId': typeof DashboardRecordRoteiroRowIdScriptIdRoute
  '/dashboard/studio': typeof DashboardStudioRoute
  '/dashboard/studio-pro': typeof DashboardStudioProRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/social': typeof DashboardSocialRoute
}
export interface FileRouteTypes { fileRoutesByFullPath: FileRoutesByFullPath; fullPaths: keyof FileRoutesByFullPath; fileRoutesByTo: FileRoutesByTo; to: keyof FileRoutesByTo; id: keyof FileRoutesById; fileRoutesById: FileRoutesById }

declare module '@tanstack/react-router' { interface FileRoutesByPath {
  '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
  '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
  '/admin/': { id: '/admin/'; path: '/'; fullPath: '/admin/'; preLoaderRoute: typeof AdminIndexRouteImport; parentRoute: typeof AdminRoute }
  '/admin/login': { id: '/admin/login'; path: '/login'; fullPath: '/admin/login'; preLoaderRoute: typeof AdminLoginRouteImport; parentRoute: typeof AdminRoute }
  '/admin/ui-textos': { id: '/admin/ui-textos'; path: '/ui-textos'; fullPath: '/admin/ui-textos'; preLoaderRoute: typeof AdminUiTextosRouteImport; parentRoute: typeof AdminRoute }
  '/dashboard/': { id: '/dashboard/'; path: '/'; fullPath: '/dashboard/'; preLoaderRoute: typeof DashboardIndexRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/profile': { id: '/dashboard/profile'; path: '/profile'; fullPath: '/dashboard/profile'; preLoaderRoute: typeof DashboardProfileRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/customers/': { id: '/dashboard/customers/'; path: '/customers'; fullPath: '/dashboard/customers/'; preLoaderRoute: typeof DashboardCustomersIndexRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/roteiros/': { id: '/dashboard/roteiros/'; path: '/roteiros'; fullPath: '/dashboard/roteiros/'; preLoaderRoute: typeof DashboardRoteirosIndexRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/roteiros/$productId': { id: '/dashboard/roteiros/$productId'; path: '/roteiros/$productId'; fullPath: '/dashboard/roteiros/$productId'; preLoaderRoute: typeof DashboardRoteirosProductIdRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/videos/': { id: '/dashboard/videos/'; path: '/videos'; fullPath: '/dashboard/videos/'; preLoaderRoute: typeof DashboardVideosIndexRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/record/$roteiroRowId/$scriptId': { id: '/dashboard/record/$roteiroRowId/$scriptId'; path: '/record/$roteiroRowId/$scriptId'; fullPath: '/dashboard/record/$roteiroRowId/$scriptId'; preLoaderRoute: typeof DashboardRecordRoteiroRowIdScriptIdRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/studio': { id: '/dashboard/studio'; path: '/studio'; fullPath: '/dashboard/studio'; preLoaderRoute: typeof DashboardStudioRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/studio-pro': { id: '/dashboard/studio-pro'; path: '/studio-pro'; fullPath: '/dashboard/studio-pro'; preLoaderRoute: typeof DashboardStudioProRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/publish': { id: '/dashboard/publish'; path: '/publish'; fullPath: '/dashboard/publish'; preLoaderRoute: typeof DashboardPublishRouteImport; parentRoute: typeof DashboardRoute }
  '/dashboard/social': { id: '/dashboard/social'; path: '/social'; fullPath: '/dashboard/social'; preLoaderRoute: typeof DashboardSocialRouteImport; parentRoute: typeof DashboardRoute }
} }

interface AdminRouteChildren { AdminLoginRoute: typeof AdminLoginRoute; AdminIndexRoute: typeof AdminIndexRoute; AdminUiTextosRoute: typeof AdminUiTextosRoute }
const AdminRouteChildren: AdminRouteChildren = { AdminLoginRoute, AdminIndexRoute, AdminUiTextosRoute }
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)
interface DashboardRouteChildren { DashboardProfileRoute: typeof DashboardProfileRoute; DashboardIndexRoute: typeof DashboardIndexRoute; DashboardRoteirosProductIdRoute: typeof DashboardRoteirosProductIdRoute; DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute; DashboardRoteirosIndexRoute: typeof DashboardRoteirosIndexRoute; DashboardVideosIndexRoute: typeof DashboardVideosIndexRoute; DashboardRecordRoteiroRowIdScriptIdRoute: typeof DashboardRecordRoteiroRowIdScriptIdRoute; DashboardStudioRoute: typeof DashboardStudioRoute; DashboardStudioProRoute: typeof DashboardStudioProRoute; DashboardPublishRoute: typeof DashboardPublishRoute; DashboardSocialRoute: typeof DashboardSocialRoute }
const DashboardRouteChildren: DashboardRouteChildren = { DashboardProfileRoute, DashboardIndexRoute, DashboardRoteirosProductIdRoute, DashboardCustomersIndexRoute, DashboardRoteirosIndexRoute, DashboardVideosIndexRoute, DashboardRecordRoteiroRowIdScriptIdRoute, DashboardStudioRoute, DashboardStudioProRoute, DashboardPublishRoute, DashboardSocialRoute }
const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren)
interface RootRouteChildren { IndexRoute: typeof IndexRoute; AdminRoute: typeof AdminRouteWithChildren; DashboardRoute: typeof DashboardRouteWithChildren }
const rootRouteChildren: RootRouteChildren = { IndexRoute, AdminRoute: AdminRouteWithChildren, DashboardRoute: DashboardRouteWithChildren }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
